package deploy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ernesto2108/forge/internal/config"
	"github.com/ernesto2108/forge/internal/frontmatter"
	"github.com/ernesto2108/forge/internal/output"
)

func Codex(cfg *config.App, paths TargetPaths) {
	target := paths.Codex
	output.Info("%s -> %s", output.Bold("Codex"), target)
	os.MkdirAll(target, 0o755)

	DeploySkillsSymlink(cfg.RepoDir, target)
	generateAgentsMD(cfg, filepath.Join(target, "AGENTS.md"))
	output.Info("  AGENTS.md -> generated from %s agents", cfg.Name)
}

func generateAgentsMD(cfg *config.App, outputPath string) {
	files := AgentFiles(cfg.RepoDir)
	if len(files) == 0 {
		return
	}

	var b strings.Builder

	fmt.Fprintf(&b, "# AGENTS.md\n\n")
	fmt.Fprintf(&b, "> Auto-generated by [%s](https://github.com/ernesto2108/%s).\n\n", capitalize(cfg.Name), cfg.Name)
	fmt.Fprintf(&b, "## Available Agents\n\n")
	fmt.Fprintf(&b, "| Agent | Role | Permission |\n")
	fmt.Fprintf(&b, "|-------|------|------------|\n")

	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		name := strings.TrimSuffix(filepath.Base(f), ".md")
		doc := frontmatter.Parse(string(data))
		desc := doc.Fields["description"]
		perm := doc.Fields["permission"]
		fmt.Fprintf(&b, "| **%s** | %s | %s |\n", name, desc, perm)
	}

	b.WriteString(`
## Agent Boundaries

- **developer** is the ONLY agent that writes production code
- **tester** is the ONLY agent that writes test files
- **dba** is the ONLY agent that creates migrations
- **devops** is the ONLY agent that touches CI/CD, Dockerfiles, and infra configs
- **pm** is the ONLY agent that creates PRDs and manages the backlog
- Agents do NOT cross boundaries — developer never writes tests, tester never writes production code

## Orchestration

For non-trivial tasks, the orchestrator triages complexity and runs agents in order:
- **Trivial** (1-2 files): direct execution, no agents
- **Medium** (3-8 files): developer → tester → qa
- **Large** (8+ files): pm → architect → developer → tester → qa → reporter
`)

	os.WriteFile(outputPath, []byte(b.String()), 0o644)
}

func capitalize(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func GenerateAgentsMD(cfg *config.App, outputPath string) {
	generateAgentsMD(cfg, outputPath)
}
